version: "3.9"

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "8000"
    volumes:
      - ./images:/app/images
      - ./logs:/logs
      - ./static:/app/static
    restart: unless-stopped


  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./images:/app/images
      - ./static:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  images:
  logs:

