services:

# --- Flask-приложение ---
  app:
    build: .
    container_name: flask_app
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
    environment:
      - SECRET_KEY=my_secret_key
    networks:
      - backend

# --- Nginx-сервер ---
  nginx:
    image: nginx:stable
    container_name: server_nginx
    ports:
      - "8080:80"
    volumes:
      - ./images:/usr/share/nginx/html/images
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
