version: "3.9"

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
      - ./static:/app/static
    depends_on:
      - db
    restart: unless-stopped


  db:
    image: postgres:13
    container_name: pg_database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backups:/backups

  # Инициализация БД — запускается один раз
  init_db:
    build: .
    container_name: init_db
    command: python init_db.py
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./images:/app/images
      - ./static:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  images:
  logs:
  db_data:
  backups:

